/** 48 players; surnames are unique so "Surname / Surname" team names never collide. */
export const PLAYER_NAMES: ReadonlyArray<readonly [first: string, last: string]> = [
  ['Maya', 'Delgado'],
  ['Tomas', 'Okafor'],
  ['Priya', 'Raman'],
  ['Jonah', 'Whitfield'],
  ['Lena', 'Sørensen'],
  ['Marcus', 'Bell'],
  ['Aiko', 'Tanaka'],
  ['Dev', 'Chaudhry'],
  ['Sofia', 'Marchetti'],
  ['Kai', 'Nakamura'],
  ['Rosa', 'Villanueva'],
  ['Elijah', 'Brooks'],
  ['Nadia', 'Haddad'],
  ['Owen', 'Gallagher'],
  ['Imani', 'Osei'],
  ['Luca', 'Ferreira'],
  ['Hana', 'Kowalski'],
  ['Theo', 'Lindqvist'],
  ['Camila', 'Reyes'],
  ['Jasper', 'Nguyen'],
  ['Zara', 'Ahmadi'],
  ['Felix', 'Moreau'],
  ['Ines', 'Castellanos'],
  ['Rafael', 'Duarte'],
  ['Noor', 'Siddiqui'],
  ['Callum', 'Reid'],
  ['Yuki', 'Hayashi'],
  ['Andre', 'Baptiste'],
  ['Sienna', 'Holloway'],
  ['Mateo', 'Quintero'],
  ['Farah', 'El-Amin'],
  ['Silas', 'Petrov'],
  ['Greta', 'Vance'],
  ['Ravi', 'Menon'],
  ['Beatriz', 'Nogueira'],
  ['Hugo', 'Andersen'],
  ['Tessa', 'McAllister'],
  ['Kofi', 'Mensah'],
  ['Elin', 'Bergström'],
  ['Nikolai', 'Volkov'],
  ['Amara', 'Ikande'],
  ['Diego', 'Salazar'],
  ['Wren', 'Fitzgerald'],
  ['Sam', 'Achterberg'],
  ['Leila', 'Farouk'],
  ['Bram', 'de Vries'],
  ['June', 'Park'],
  ['Ezra', 'Cohen'],
];

export const ORGANIZER_NAMES: ReadonlyArray<readonly [first: string, last: string]> = [
  ['Harper', 'Lindgren'],
  ['Mo', 'Adeyemi'],
];
