// Next's ambient types. `next-env.d.ts` is generated by `next dev`/`next build` and
// gitignored; this committed file keeps `tsc -b` correct in a fresh clone.
/// <reference types="next" />
/// <reference types="next/image-types/global" />
